name = "send-email"
main = "src/index.js"
compatibility_date = "2023-11-21"
type = "javascript"
account_id = "4434a77f340af790b9d0a5cdcce6bed8"
workers_dev = true
route = ""
zone_id = "5d388b2e5c2861b47edf3f7859774d27"
node_compat = true # Enable Node.js compatibility